% Run the 6-DOF Simulink model and export one canonical NED telemetry CSV.
simmulation = sim("hopper_6dof_NED_v2.slx");

% Position z is the model's up-positive altitude. A-D are scalar-first body-to-NED quaternions.
data = [ ...
    simmulation.tout, ...
    simmulation.x.data, simmulation.y.data, simmulation.z.data, ...
    simmulation.thrust.data, ...
    simmulation.A.data, simmulation.B.data, simmulation.C.data, simmulation.D.data, ...
    simmulation.fuel_mass.data, simmulation.ox_mass.data, simmulation.u.Data, ...
    simmulation.cg.data(:,1), simmulation.cg.data(:,2), simmulation.cg.data(:,3), ...
    simmulation.velocity.data(:,1), simmulation.velocity.data(:,2), simmulation.velocity.data(:,3) ...
];

names = {'time', 'north', 'east', 'up', 'thrust', 'q0', 'q1', 'q2', 'q3', ...
    'fuel_mass', 'ox_mass', 'control', 'cg_x', 'cg_y', 'cg_z', 'vn', 've', 'vd'};
writetable(array2table(data, 'VariableNames', names), 'godotData.csv');
